feature/delete-for-each-entity
Shady712/PetProject pull request #24
Opened 2022-01-21 18:58 UTC by aleksgright

added methods for deleting for each entity and tests for it
added InviteTest.java
added InviteUtils.java
added test for creating invite

2022-01-21 21:30 UTC, Shady712 requested changes

2022-01-21 21:30 UTC, Shady712 commented on src/test/java/com/sasd/eventor/utils/InviteUtils.java
> +    public static InviteCreateDto makeInviteCreateDto(Long receiverId, Long eventId) {
го в DSL, make в методе не очень хорошо звучит

2022-01-21 21:30 UTC, Shady712 commented on src/test/java/com/sasd/eventor/event/EventDeleteTest.java
> +public class EventDeleteTest extends EventTest {
во всех тестах не хватает проверки того, что после удаление сущность действительно удалена. Не хватает того, что удаление несуществующего ничего не делает (не бросает эксепшн или не возвращает false)

2022-01-21 21:30 UTC, Shady712 commented on src/main/java/com/sasd/eventor/services/EventService.java
> +    public void deleteById(Long id){
давай все delete будут внизу, последними методами класса

2022-01-21 21:30 UTC, Shady712 commented on src/main/java/com/sasd/eventor/controllers/EventController.java
> +    public void deleteById(@RequestParam Long id) {
Две глобальных проблемы:
1. Давай либо возвращать Boolean (удалось ли удалить), либо void и выкидывать эксепшн если не удалось удалить
2 (blocker) Надо прикрутить авторизацию, чтобы Петя фориком не прошелся по id и не дропнул нам базу

2022-01-24 17:16 UTC, aleksgright commented on src/test/java/com/sasd/eventor/utils/InviteUtils.java
> +    public static InviteCreateDto makeInviteCreateDto(Long receiverId, Long eventId) {
куда?

2022-01-24 18:27 UTC, Shady712 requested changes

2022-01-24 18:27 UTC, Shady712 commented on src/main/java/com/sasd/eventor/controllers/EventController.java
> +    }
🚫 Неверная логика. Теперь залогиненный пользователь может удалить кого угодно. То есть Вася может удалить Свету, если знает её id. И Вася может вообще всю базу удалить.

2022-01-24 18:27 UTC, Shady712 commented on src/test/java/com/sasd/eventor/utils/InviteUtils.java
> +    public static InviteCreateDto makeInviteCreateDto(Long receiverId, Long eventId) {
https://ru.wikipedia.org/wiki/DSL
makeInviteCreatoDto(...) -> inviteCreateDto(...)

2022-01-25 20:27 UTC, closed without merging