invite
Shady712/PetProject pull request #33
Opened 2022-01-29 11:09 UTC by ElderEclair

added:
findAllIncoming
acceptInvite
rejectInvite
inviteResponseDto instead of invite

updated:
create

2022-01-29 11:32 UTC, Shady712 requested changes

2022-01-29 11:32 UTC, Shady712 commented on src/main/java/com/sasd/eventor/controllers/InviteController.java
> +                InviteResponseDto.class);
не хватает переноса строки перед );

2022-01-29 11:32 UTC, Shady712 commented on src/main/java/com/sasd/eventor/model/dtos/InviteResponseDto.java
> +    private Long EventId;
👎 названия полей с маленькой буквы.....

2022-01-29 11:32 UTC, Shady712 commented on src/main/java/com/sasd/eventor/model/dtos/InviteResponseDto.java
> +    private Long EventId;
Очень странный подход. Если в сущности хранятся другие сущности, для которых есть ResponseDto, то почему здесь мы плодим какую-то непонятную логику и обязанность фронта ходить к нам по дополнительным ручкам, вместо того, чтобы воспользоваться как раз таки уже написанными ResponseDto

2022-01-29 11:32 UTC, Shady712 commented on src/main/java/com/sasd/eventor/controllers/InviteController.java
> +                                .orElseThrow(() -> new EventorException("You are not Authorized")))
не хватает переноса строки перед последней )

2022-01-29 11:32 UTC, Shady712 commented on src/main/java/com/sasd/eventor/controllers/InviteController.java
>          var event = eventService.findById(eventId);
Давай соблюдать нейминг: если переменная имеет тип `Optional<Entity>`, то ее имя должно быть `foundEntity`

2022-01-29 11:32 UTC, Shady712 commented on src/main/java/com/sasd/eventor/controllers/InviteController.java
> +    private Invite getValidatedInvite(Long id, String recievevrJwt, Set<RequestStatus> statuses) {
`recievevrJwt` -> `receiverJwt` : Intellij подчеркивает зеленым опечатки

2022-01-29 11:32 UTC, Shady712 commented on src/main/java/com/sasd/eventor/controllers/InviteController.java
>      }
Вау, сделать такой метод отличная идея! 👍

2022-01-29 11:32 UTC, Shady712 commented on src/main/java/com/sasd/eventor/controllers/InviteController.java
> +    @Transactional
надо проверить, нужна ли транзакция

2022-01-29 11:32 UTC, Shady712 commented on src/main/java/com/sasd/eventor/controllers/InviteController.java
> +    @Transactional
надо проверить, нужна ли транзакция

2022-01-29 11:37 UTC, ElderEclair commented on src/main/java/com/sasd/eventor/controllers/InviteController.java
> +    private Invite getValidatedInvite(Long id, String recievevrJwt, Set<RequestStatus> statuses) {
кринж, я жту ошибку делаю абсолютно каждый раз когда пишу это слово...

2022-01-29 11:46 UTC, ElderEclair commented on src/main/java/com/sasd/eventor/model/dtos/InviteResponseDto.java
> +    private Long EventId;
Ты точно также в фр делал

2022-01-30 01:33 UTC, Shady712 requested changes

2022-01-30 01:33 UTC, Shady712 commented on src/main/java/com/sasd/eventor/controllers/InviteController.java
> +    private Invite getValidatedInvite(Long id, String receivevrJwt, Set<RequestStatus> statuses) {
все еще опечатка receivevr

2022-01-30 01:33 UTC, Shady712 commented on src/main/java/com/sasd/eventor/controllers/UserController.java
>          }
тут не хватает удаления всех входящих инвайтов

2022-01-30 01:33 UTC, Shady712 commented on src/main/java/com/sasd/eventor/services/converters/InviteEntityToInviteResponseDtoConverter.java
> +    @Override
нет пустой строки между полями и методами

2022-01-30 01:33 UTC, Shady712 commented on src/test/java/com/sasd/eventor/AbstractTest.java
> +    }
метод выглядит как hueta.com

2022-01-30 01:33 UTC, Shady712 commented on src/test/java/com/sasd/eventor/AbstractTest.java
> +    protected UserService userService;
обойдемся без инъекции сервисного слоя в тесты

2022-01-30 01:33 UTC, Shady712 commented on src/test/java/com/sasd/eventor/invite/InviteUpdateTest.java
> +public class InviteUpdateTest extends InviteTest {
Тесты падают

2022-01-30 18:41 UTC, ElderEclair commented on src/main/java/com/sasd/eventor/controllers/EventController.java
> +        if (!foundEvent
какой ужас, щас поправлю

2022-01-30 18:42 UTC, ElderEclair commented on src/main/java/com/sasd/eventor/controllers/EventController.java
> +                .findById(id).orElseThrow(() -> new EventorException("Event with provided id does not exist"));
какой ужас, щас поправлю

2022-01-30 18:44 UTC, ElderEclair commented on src/test/java/com/sasd/eventor/friendrequest/FriendRequestUpdateTest.java
> +        abstractAcceptInviteTest((id, receiverJwt) -> friendRequestController.acceptRequest(id, receiverJwt));
а ой

2022-01-31 10:08 UTC, aleksgright requested changes

2022-01-31 10:08 UTC, aleksgright commented on src/test/java/com/sasd/eventor/invite/InviteUpdateTest.java
> +        registerUser(invalidReceiver);
getJwt регистрирует пользователя

2022-01-31 17:01 UTC, Shady712 commented on src/test/java/com/sasd/eventor/invite/InviteDeleteTest.java
> +                        getJwt(validUserRegisterDto())
`getJwt(validUserRegisterDto())` -> `getJwt()`

2022-01-31 17:06 UTC, Shady712 commented on src/test/java/com/sasd/eventor/invite/InviteUpdateTest.java
> +    }
Очень похоже на тесты `FriendRequestUpdateTest`. Можно это все сделать на дженериках, чтобы копипасты не было. 🤡

2022-01-31 17:08 UTC, Shady712 commented on src/test/java/com/sasd/eventor/invite/InviteCreateTest.java
>      @Test
А кейс, когда создается повторный инвайт?

2022-01-31 17:10 UTC, Shady712 commented on src/main/java/com/sasd/eventor/controllers/EventController.java
> +    }
не вижу тестов - не верю, что функционал рабочий

2022-02-01 14:46 UTC, Shady712 requested changes

2022-02-01 14:46 UTC, Shady712 commented on src/main/java/com/sasd/eventor/controllers/UserController.java
> +        var foundUser = userService
нейминг страдает, foundUser -> user

2022-02-01 14:46 UTC, Shady712 commented on src/test/java/com/sasd/eventor/event/EventFindTest.java
> +    }
```suggestion
    @Test
    public void findAllGuests() {
        var event = eventController.create(validEventCreateDto(VALID_NAME));
        assert Stream.of(
                validUserRegisterDto(),
                validUserRegisterDto(),
                validUserRegisterDto()
        ).map(dto -> inviteController.acceptInvite(
                        inviteController.createInvite(validInviteCreateDto(registerUser(dto).getId(), event.getId())).getId(),
                        userController.createJwt(dto.getLogin(), dto.getPassword())
                )
        ).map(InviteResponseDto::getReceiver).toList().equals(eventController.findAllGuests(event.getId()));
        assert !eventController.findAllGuests(event.getId()).contains(registerUser());
    }
```

2022-02-01 14:46 UTC, Shady712 commented on src/main/java/com/sasd/eventor/controllers/InviteController.java
> +    public InviteResponseDto createInvite(@RequestBody @Valid InviteCreateDto inviteCreateDto) {
не хватает проверки, что приглашает создатель ивента

2022-02-01 16:41 UTC, Shady712 approved these changes

2022-02-01 16:54 UTC, Shady712 approved these changes

2022-02-01 16:54 UTC, merged