feature/delete
Shady712/PetProject pull request #36
Opened 2022-01-30 13:06 UTC by aleksgright

added salt service

2022-01-31 16:43 UTC, Shady712 requested changes

2022-01-31 16:43 UTC, Shady712 commented on src/main/java/com/sasd/eventor/controllers/UserController.java
> +            throw new EventorException("Invalid login or password");
Тут же просто Invalid password, логин выше проверен

2022-01-31 16:43 UTC, Shady712 commented on src/main/java/com/sasd/eventor/model/entities/User.java
> +    }
думаю этот метод должен быть в `SaltService`, иначе мы нарушаем SRP: у нас класс `User` будет меняться не только по причине добавления новых данных, но и если захотим соль поменять. Еще тут какой-то magic number

2022-01-31 16:43 UTC, Shady712 commented on src/main/java/com/sasd/eventor/model/entities/User.java
> +    public String getSalt() {
так называть метод крайне нежелательно, это же не геттер по сути, а какая-то логика

2022-01-31 16:43 UTC, Shady712 commented on src/main/java/com/sasd/eventor/services/utils/SaltService.java
> +    private static final String SECRET = "OdinDlyaLudeiDrugoiDlyMonstrov";
другой то для чудовищ

2022-01-31 16:43 UTC, Shady712 commented on src/main/java/com/sasd/eventor/services/utils/SaltService.java
> +    public String createHash(String password, String salt) {
этот метод может быть `private`

2022-01-31 16:43 UTC, Shady712 commented on src/main/java/com/sasd/eventor/services/utils/SaltService.java
> +        }
копипаста

2022-01-31 16:43 UTC, Shady712 commented on src/main/java/com/sasd/eventor/services/utils/SaltService.java
> +        }
копипаста. У тебя методы объявленны перегруженными, а ты их не перегрузил, а просто разными сделал, хотя они одинаковые

2022-01-31 16:43 UTC, Shady712 commented on src/test/java/com/sasd/eventor/user/UserRegistrationTest.java
> +
?????

2022-01-31 16:43 UTC, Shady712 commented on src/test/java/com/sasd/eventor/user/UserRegistrationTest.java
> +import com.sasd.eventor.services.utils.SaltService;
unused import

2022-01-31 16:43 UTC, Shady712 commented on src/test/java/com/sasd/eventor/user/UserRegistrationTest.java
>  public class UserRegistrationTest extends UserTest {
Так в принципе думаю можно не тестить новый сервис. Регрессионного прохождения уже написанных тестов должно хватать

2022-01-31 20:09 UTC, aleksgright commented on src/main/java/com/sasd/eventor/controllers/UserController.java
> +            throw new EventorException("Invalid login or password");
обычно вроде не пишут что именно неверно, а у меня инвалид логин потому что я дебажил))

2022-01-31 20:10 UTC, aleksgright commented on src/main/java/com/sasd/eventor/services/utils/SaltService.java
> +    private static final String SECRET = "OdinDlyaLudeiDrugoiDlyMonstrov";
фор риал, поправил

2022-02-01 12:01 UTC, Shady712 approved these changes

2022-02-01 12:01 UTC, merged